---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yuyou.
--- DateTime: 2024/5/25 22:19
---



SHMain =  {}
local L = AceLibrary("AceLocale-2.2"):new("SummonHelper")
function SHMain:OnInitialize()

    self.position = {
        point=SummonHelper.opt.point,
        relativePoint=SummonHelper.opt.relativePoint,
        xOfs=SummonHelper.opt.xOfs,
        yOfs=SummonHelper.opt.yOfs
    }
    --self.candidate = {}
    if not self.mf then
        self:SetUpMainFrame()
    end
    self:Flush()
end


function SHMain:SetUpMainFrame()
    if self.mf then
        return
    end
    local f = CreateFrame("Frame", "SHMainFrame", UIParent)
    f:SetWidth(200)
    f:SetHeight(170)
    f:ClearAllPoints()
    f:SetPoint(self.position.point, UIParent, self.position.relativePoint, self.position.xOfs, self.position.yOfs)
    -- background
    f:SetBackdrop({
        bgFile = "Interface\\Tooltips\\UI-Tooltip-Background", tile = true, tileSize = 1,
        edgeFile = "Interface\\AddOns\\G_SummonHelper\\Textures\\border", edgeSize = 32,
        insets = {left = 1, right = 1, top = 20, bottom = 1},
    })
    f:SetBackdropColor(24/255, 24/255, 24/255)
    f:SetBackdropBorderColor(0/255, 0/255, 255/255)
    f:SetFrameStrata("LOW")
    -- drag and drop
    f:EnableMouse(true)
    f:SetClampedToScreen(true) -- can't move it outside of the screen
    f:RegisterForDrag("LeftButton")
    f:SetMovable(true)
    f:SetScript("OnDragStart", function() this:StartMoving() end)
    f:SetScript("OnDragStop", function()
        this:StopMovingOrSizing()
        local point, _, relativePoint, xOfs, yOfs = this:GetPoint()
        self.position.point = point
        self.position.relativePoint = relativePoint
        self.position.xOfs = xOfs
        self.position.yOfs = yOfs
    end)

    f.textures = {}
    f.fontStrs = {}
    f.buttons = {}

    local fontStr= f:CreateFontString(nil, "OVERLAY")
    fontStr:SetFontObject("GameFontNormal")
    fontStr:SetPoint("TOP", f,"TOP", 0 ,-10)
    fontStr:SetHeight(20)
    fontStr:SetText(SummonHelper.Prefix)
    fontStr:SetShadowOffset(.8, -.8)
    fontStr:SetShadowColor(0, 0, 0, 1)
    f.fontStrs["head"] = fontStr

    local bt = CreateFrame("Button", "announceButton", f)
    bt:SetPoint("TOP" , f, "TOP", -80,  -10)
    bt:SetNormalTexture("Interface\\AddOns\\G_SummonHelper\\Textures\\report")
    bt:SetHighlightTexture("Interface\\AddOns\\G_SummonHelper\\Textures\\report")
    bt:SetWidth(20)
    bt:SetHeight(20)
    bt:RegisterForClicks("LeftButtonUp")
    bt:SetScript("OnClick", function()
        local playerZone = GetZoneText()..GetSubZoneText()
        local chatType = GetNumRaidMembers() > 0 and "RAID" or "PARTY"
        SendChatMessage(buildMessage(L["团队打字打关键词被拉到 %s"], playerZone ), chatType)
    end)
    f.buttons["announceButton"] = bt

    local bt = CreateFrame("Button", "closeButton", f)
    bt:SetPoint("TOP" , f, "TOP", 90,  -10)
    bt:SetNormalTexture("Interface\\Buttons\\UI-Panel-MinimizeButton-Down")
    bt:SetHighlightTexture("Interface\\Buttons\\UI-Panel-MinimizeButton-Up")
    bt:SetWidth(20)
    bt:SetHeight(20)
    bt:RegisterForClicks("LeftButtonUp")
    bt:SetScript("OnClick", function()
        self.mf:Hide()
    end)
    f.buttons["closeButton"] = bt

    --local texture = f:CreateTexture(nil, "ARTWORK")
    --texture:SetTexture("Interface\\TargetingFrame\\UI-TargetingFrame-BarFill")
    --texture:SetWidth(f:GetWidth() - 10)
    --texture:SetHeight(4)
    --texture:SetPoint("TOP", f, "TOP", 0, -35)
    --f.textures["headLine"] = texture

    for i = 1, 5 do
        local bt = CreateFrame("Button", "removeButton", f)
        bt.index= i
        bt:SetPoint("TOP" , f, "TOP", -85,  -20 - i * 25)
        bt:SetNormalTexture("Interface\\Icons\\spell_chargenegative")
        bt:SetHighlightTexture("Interface\\Icons\\spell_chargenegative")
        bt:SetWidth(20)
        bt:SetHeight(20)
        bt:RegisterForClicks("LeftButtonUp")
        bt:SetScript("OnClick", function()
            local name = self.mf.fontStrs["body"..this.index]:GetText()
            SummonHelper:RemoveFonc(name)
        end)
        f.buttons["removeButton"..i] = bt

        local bt = CreateFrame("Button", "summonButton", f)
        bt.index= i
        bt:SetPoint("TOP" , f, "TOP", 85, -20 - i * 25)
        bt:SetNormalTexture("Interface\\Icons\\spell_shadow_twilight")
        bt:SetHighlightTexture("Interface\\Icons\\spell_shadow_twilight")
        bt:SetWidth(20)
        bt:SetHeight(20)
        bt:RegisterForClicks("LeftButtonUp")
        bt:SetScript("OnClick", function()
            self.currentT = self.mf.fontStrs["body"..this.index]:GetText()
            SummonHelper:SummonFonc(self.currentT)
        end)
        f.buttons["summonButton"..i] = bt
        local fontStr= f:CreateFontString(nil, "OVERLAY")
        fontStr:SetFontObject("GameFontNormal")
        fontStr:SetPoint("TOP", f,"TOP", 0 , -20 - i * 25)
        fontStr:SetText("N/A")
        fontStr:SetShadowOffset(.8, -.8)
        fontStr:SetShadowColor(0, 0, 0, 1)
        f.fontStrs["body"..i] = fontStr

        local texture = f:CreateTexture(nil, "ARTWORK")
        texture:SetTexture("Interface\\TargetingFrame\\UI-TargetingFrame-BarFill")
        texture:SetWidth(f:GetWidth() - 10)
        texture:SetHeight(4)
        texture:SetPoint("TOP", f, "TOP", 0, -35 - i * 25 -5)
        f.textures["body"..i] = texture

    end
    self.mf = f
end
function SHMain:Flush()
    for i = 1, 5 do
        local t = SummonHelper.SummonList[i]
        if t then
            self.mf.buttons["removeButton"..i]:Show()
            self.mf.fontStrs["body"..i]:SetText(t)
            self.mf.fontStrs["body"..i]:Show()
            self.mf.buttons["summonButton"..i]:Show()
            self.mf.textures["body"..i]:Show()
        else
            self.mf.buttons["removeButton"..i]:Hide()
            self.mf.fontStrs["body"..i]:Hide()
            self.mf.buttons["summonButton"..i]:Hide()
            self.mf.textures["body"..i]:Hide()
        end
    end
end

